FROM ubuntu:latest
MAINTAINER sumeet.mankoo@gmail.com

RUN apt-get update && apt-get install -y cron logrotate

ADD crontab /crontab-src
ADD logrotate.conf /etc/logrotate.conf
RUN chmod 644 /etc/logrotate.conf

RUN crontab /crontab-src
RUN touch /tmp/dt.log

CMD cron && tail -f /tmp/dt.log